name: zVoteParty
author: Maxlego08
main: fr.maxlego08.zvoteparty.ZVotePartyPlugin
softdepend: [PlaceholderAPI, Votifier, zMenu]
version: '${project.version}'
website: https://groupez.dev/resources/zvoteparty.124
api-version: 1.20
folia-supported: true
commands: